name: Tests

on: pull_request

jobs:
  ruff:
    name: Ruff
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.11.6"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --dev
      - name: Run ruff format
        run: uv run ruff format --check
      - name: Run ruff check
        run: uv run ruff check

  tests:
    name: Tests (Python ${{ matrix.python-version }}, ${{ matrix.runs-on }})
    timeout-minutes: ${{ matrix.timout-minutes }}
    runs-on: ${{ matrix.runs-on }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        runs-on: ["ubuntu-latest", "ubuntu-22.04-arm"]
        experimental: [false]
        timout-minutes: [10]
        include:
          - python-version: "3.15"
            runs-on: "ubuntu-22.04-arm"
            experimental: true
            timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.11.6"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install the project
        run: uv sync --dev --python ${{ matrix.python-version }}
      - name: Run pytest
        run: uv run pytest tests

